# Generated by Django 3.1.7 on 2021-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default_avatar.png', upload_to='user_avatar'),
        ),
    ]
