# Generated by Django 3.1.7 on 2021-05-23 08:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0003_postwall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=tinymce.models.HTMLField(default='Just write something about you'),
        ),
    ]
