# Generated by Django 3.1.7 on 2021-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0004_auto_20210523_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Jakis tekst'),
        ),
    ]
