# Generated by Django 3.1.7 on 2021-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0005_auto_20210523_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwall',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
