# Generated by Django 3.1.7 on 2021-05-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0008_auto_20210523_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwall',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubek.profile'),
        ),
    ]
