# Generated by Django 3.1.7 on 2021-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0012_auto_20210523_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
