# Generated by Django 3.1.7 on 2021-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0013_profile_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
