# Generated by Django 3.1.7 on 2021-06-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0018_auto_20210614_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='like_post',
            field=models.ManyToManyField(to='ubek.PostWall'),
        ),
    ]
