# Generated by Django 3.1.7 on 2021-06-14 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubek', '0019_auto_20210614_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwall',
            name='like_post',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
